./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 1 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 1 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 1 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 2 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 2 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 2 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 4 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 4 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 4 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 8 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 8 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 8 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 16 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 16 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 16 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 32 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 32 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 32 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 64 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 64 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Google -graph-url https://snap.stanford.edu/data/web-Google.txt.gz -threads 64 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 1 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 1 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 1 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 2 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 2 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 2 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 4 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 4 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 4 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 8 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 8 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 8 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 16 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 16 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 16 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 32 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 32 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 32 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 64 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 64 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-BerkStan -graph-url https://snap.stanford.edu/data/web-BerkStan.txt.gz -threads 64 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 1 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 1 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 1 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 2 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 2 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 2 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 4 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 4 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 4 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 8 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 8 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 8 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 16 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 16 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 16 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 32 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 32 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 32 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 64 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 64 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-NotreDame -graph-url https://snap.stanford.edu/data/web-NotreDame.txt.gz -threads 64 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 1 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 1 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 1 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 2 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 2 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 2 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 4 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 4 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 4 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 8 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 8 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 8 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 16 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 16 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 16 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 32 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 32 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 32 -analysis-type hpc-performance && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 64 -analysis-type performance-snapshot && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 64 -analysis-type hotspots && 
./scripts/execute_single_bench.sh -graph-name web-Stanford -graph-url https://snap.stanford.edu/data/web-Stanford.txt.gz -threads 64 -analysis-type hpc-performance